#variables:
# JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"  # Ensure it's pointing to the JDK, not JRE
# MAVEN_HOME: "/usr/share/maven"
# PATH: "$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH"
#
#before_script:
#  - export JAVA_HOME=$JAVA_HOME  # Ensures JAVA_HOME is set in the job environment
#  - java -version  # Confirm Java version
#  - mvn --version  # Confirm Maven setup

stages:   # these stages (jobs) forms the CICD pipeline
  - mavenbuild      # this is a JOB to build your Springboot application
  - maventest       # this is a JOB to run tests in your Springboot application (it's okay you don't have any test for now)
  - mavendeploy     # this is a JOB to deploy your Springboot application on your server
  - androidbuild    # this is a JOB to build your Android application
  - androidtest     # this is a JOB to run tests in your Android application (it's okay you don't have any test for now)

maven-build:
  stage: mavenbuild     # one of the stages listed above
  tags:                 # to specify which runner to execute this job
    - springboot_tag    # change to your runner's tag
  variables:  # Move these to the top-level `variables` block for consistency
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"
  script:               # what to execute for this job
    - cd Backend/workout        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - export JAVA_HOME=/usr/lib/jvm/jre-17-openjdk  # Set JAVA_HOME to the correct path
#    - mvn clean compile -U -Djava.home=$JAVA_HOME
    - mvn -version
    - mvn package -U -Djava.home=$JAVA_HOME    # maven package
  artifacts:            # where to output the packaged jar file, change 'Backend' to to where you have the pom.xml
    paths:
      - Backend/workout/target/*.jar # change 'Backend' to where you have 'target' (do not add a / in the beginning)
  only:
    refs:
      - main            # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/workout/**/*    # more specifically - only when changes are made inside the 'Backend' folder

maven-test:
  stage: maventest     # one of the stages listed above
  tags:
    - springboot_tag   # change to your runner's tag
  script:
    - cd Backend/workout       # change 'Backend' to where you have the pom.xml (do not add / in the beginning)
    - export JAVA_HOME=/usr/lib/jvm/jre-17-openjdk  # Set JAVA_HOME to the correct path
    - mvn test -U -Djava.home=$JAVA_HOME       # maven test
    - cd target/
    - sudo ls
  only:
    refs:
      - main            # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/workout/**/*    # more specifically - only when changes are made inside the 'Backend' folder

auto-deploy:
  stage: mavendeploy    # one of the stages listed above
  tags:
    - springboot_tag      # change to your runner's tag
  script:               # script to run the deployment service you created
    - cd Backend/workout        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
#    - export JAVA_HOME=/usr/lib/jvm/jre-17-openjdk  # Set JAVA_HOME to the correct path
#    - mvn clean compile -U -Djava.home=$JAVA_HOME
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
    - sudo systemctl restart mariadb  # or mariadb

  only:
    refs:
      - main            # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/workout/**/*    # more specifically - only when changes are made inside the 'Backend' folder
 
android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
   - andriod_tag                   # <-- change to your runner's tag
  before_script:                    # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend                   # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew build
  only:
    refs:
      - main
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - andriod_tag                  # <-- change to your runner's tag
  before_script:                   # change 'Frontend' to where you have 'gradlew'
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend                  # change 'Frontend' to where you have 'gradlew' (do not add / in the beginning)
    - ./gradlew test
  only:
    refs:
      - main
    changes:
      - Frontend/**/*